site_name: TP eServices
site_description: Les Travaux Pratiques du cours eServices
site_author: Lilia Sfaxi
site_url: http://INSATunisia.github.io/TP-eServices/

# Repository
repo_name: INSATunisia/TP-eServices
repo_url: https://github.com/INSATunisia/TP-eServices

# Copyright
copyright: 'Copyright &copy; 2017 - 2018 Lilia Sfaxi'

# Theme directory
theme_dir: material

theme:
  name: 'material'
  feature:
    tabs: false
  palette:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
    accent: Amber
    primary: Pink
  logo: 'img/logo.png'
  favicon: 'img/favicon.ico'
  language: 'fr'


# Options
extra:
  feature:
    tabs: false
  palette:
    accent: Amber
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: 'img/logo.png'

  social:
    - type: globe
      link: http://liliasfaxi.wix.com/liliasfaxi
    - type: github-alt
      link: https://github.com/liliasfaxi
    - type: twitter
      link: https://twitter.com/lillitou
    - type: linkedin
      link: https://www.linkedin.com/in/liliasfaxi/

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - abbr
  - admonition
  - attr_list
  - def_list
  - codehilite
  - fenced_code
  - fontawesome_markdown
  - nl2br
  - tables

# Page tree
pages:
   - 'index.md'
   - TP1 - Services Web REST et SOAP avec Talend: 'tp1.md'
   - TP2 - Orchestration de Services avec Camunda: 'tp2.md'
   - TP3 - Mise en Place d’un ESB avec Talend ESB: 'tp3.md'
   - TP4 - Microservices avec Spring Boot et Spring Cloud: 'tp4.md'
   - TP5 - API Management avec Atom et Anypoint: 'tp5.md'

extra_javascript: []
extra_css: []
use_directory_urls: true

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
